version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - database

  database:
    image: public.ecr.aws/docker/library/mysql:5.7.41
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpassword"
      - "MYSQL_USER=dbuser"
      - "MYSQL_PASSWORD=dbpassword"
      - "MYSQL_DATABASE=mylinx_jetstream"
    volumes:
      - db-data:/var/lib/mysql

  npm:
    image: public.ecr.aws/docker/library/node:14.21.3-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    # entrypoint:
    #   - ./docker/node_start.sh


volumes:
  db-data: ~

